version: '3.4'

services:

  nosqldata:
    image: mongo

  sporty.services.groups:
    image: ${DOCKER_REGISTRY-}sportyservicesgroups
    build:
      context: .
      dockerfile: Services/Sporty.Services.Groups/Dockerfile
    depends_on:
      - nosqldata

  sporty.services.users:
    image: ${DOCKER_REGISTRY-}sportyservicesusers
    build:
      context: .
      dockerfile: Services/Sporty.Services.Users/Dockerfile
    depends_on:
      - nosqldata

